server:
  port: 8088
  servlet:
    context-path: /quartz



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz_task?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # mapper.xml文件的位置
  type-aliases-package: com.lee.quartz_task.model # 对实体所在的包进行扫描
  global-config:
    db-config: # 字段策略
      table-underline: true # 驼峰下划线转换
      id-type: auto
      field-strategy: default
      db-type: mysql
      logic-delete-value: 0
      logic-not-delete-value: 1
